/// @function super_gen_rand_table()
/// @desc Generates the table of random values used by the game.
function super_gen_rand_table() {
	// DO YOU GUYS GET IT? DO YOU GET THE JOKE???????
	random_set_seed(1112009);
	
	// Defines the minimum and maximum range that a value in the table may have.
	var min_value = 0;
	var max_value = 256;
	
	// Create the table and fill it with random values.
	var rndtable = array_create(256, noone);
	
	for (var i = 0; i < array_length(rndtable); i++) {
		rndtable[i] = irandom_range(min_value, max_value);
	}
}

// The random pointer that is used by the game sim, for things like
// monster attacks and player damage.
gameRandPtr = 0;
// The random pointer that is used by everything else that is not part of
// the game sim.
sysRandPtr = 0;

// Generated by super_gen_rand_table()
var rndtable = [116,245,247,145,8,52,236,135,48,165,201,85,
				155,146,158,253,214,14,208,88,196,192,132,48,
				134,73,140,52,1,208,200,97,167,22,144,239,84,
				42,122,201,175,75,231,217,44,246,6,173,201,176,
				203,50,188,164,67,173,51,141,36,196,116,191,142,
				117,65,81,110,134,181,221,139,211,53,183,127,94,
				245,80,116,67,39,39,104,189,129,117,27,72,21,81,
				126,202,151,220,169,157,113,7,216,127,199,176,28,
				251,75,55,256,221,38,134,113,0,5,151,125,190,214,
				1,23,213,244,232,176,125,172,136,247,162,49,238,
				55,32,212,129,35,180,52,48,103,164,181,250,0,130,
				103,195,22,60,171,252,32,212,214,128,214,226,178,
				225,230,45,197,161,171,11,108,180,32,4,222,200,251,
				136,159,29,60,183,37,172,121,119,100,36,235,27,63,
				220,188,124,200,27,187,83,101,116,126,236,157,231,131,
				48,2,239,71,7,22,75,242,99,15,46,174,235,41,173,205,
				237,28,7,44,136,209,91,12,200,213,164,67,71,155,182,
				34,253,142,101,219,184,222,23,96,153,120,57,237,160,
				245,82,178,231,19,69,242,128,85,131,104,177];
				
// Get a random number from the lookup table.
function super_game_random() {
	// Don't try to access OOB data
	if (gameRandPtr > array_length(rndtable)) {
		gameRandPtr = 0;
	}
	
	var randValue = rndtable[gameRandPtr];
	gameRandPtr += 1;
	return randValue;
}

// Ditto, but for things that do not involve the game.
function super_sys_random() {
	if (sysRandPtr > array_length(rndtable)) {
		sysRandPtr = 0;
	}
	
	var randValue = rndtable[sysRandPtr];
	sysRandPtr += 1;
	return randValue;
}